name: Tests

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and test
        run: cd auth && npm install && npm run test:ci
